name: basic-build
run-name: ${{ github.actor }} is building ErnirAngular
on:
  push:
    branches: [main] # Only run on pushes to main
  pull_request:
    types: [opened, synchronize, reopened] # Run on PR events
jobs:
  run-build:
    name: basic-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: "latest"
      - run: npm install
      - run: npm run collect-recipes
      - run: npm run build
      - run: npx prettier --check .
