name: deploy
run-name: ${{ github.actor }} is deploying ErnirAngular
on:
  push:
    branches:
      - main
      - auto-deploy
jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.ERNIR_ANGULAR_DEPLOY }}
      - uses: actions/setup-node@v4
        with:
          node-version: "latest"
      - run: npm install
      - run: npm run deploy
