name: deploy
run-name: ${{ github.actor }} is deploying ErnirAngular
on:
  workflow_run:
    workflows: [ "basic-build" ]
    types:
      - completed
    branches:
      - main
      - auto-deploy
jobs:
  run-build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: "latest"
      - run: npm run deploy
