name: deploy
run-name: ${{ github.actor }} is deploying ErnirAngular
on:
  push:
    branches:
      - main
      - auto-deploy
permissions:
  contents: write
  pull-requests: write
jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          repository: 'ernir/ernir-angular'
      - uses: actions/setup-node@v4
        with:
          node-version: "latest"
          token: ${{ secrets.ERNIR_ANGULAR_DEPLOY }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: npm install
      - run: npm run deploy
